LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := reanimated
LOCAL_CFLAGS := -DFOLLY_NO_CONFIG -DFOLLY_MOBILE=1 -DFOLLY_USE_LIBCPP=1 -DFOLLY_CFG_NO_COROUTINES=1
LOCAL_CPPFLAGS := -std=c++17
include $(BUILD_SHARED_LIBRARY) 